<a href="https://colab.research.google.com/github/harifaly/Python_for_data_science/blob/main/_numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
print('hello world')

hello world


In [6]:
import numpy as np

# ARRAY

In [7]:
table1=np.array([1,2,3,4])

In [8]:
print (table1)

[1 2 3 4]


In [9]:
table2=np.array([1,2,3])

In [10]:
print(table2)

[1 2 3]


In [11]:
table3=np.zeros((2,3))

In [12]:
table3.shape

(2, 3)

In [13]:
print(table3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
table4=np.ones((2,2))

In [15]:
print(table4)

[[1. 1.]
 [1. 1.]]


In [16]:
table4=np.ones((4,5))

In [17]:
print(table4)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
table5=np.random.randn(5)
table6=np.random.randn(5,2)

In [19]:
print("TABLE 5:\n",table5)
print("TABLE 6:\n",table6)

TABLE 5:
 [-1.26361846 -0.87393674  1.92160421  0.13657918  0.75476823]
TABLE 6:
 [[ 1.12972407  0.47303168]
 [-1.57737226 -1.80188637]
 [-0.25943838  0.01201075]
 [-0.78337942  0.17239404]
 [ 0.78483654 -0.60156169]]


In [20]:
stack1= np.array([1,2,3,4])
stack2= np.array([5,6,7,8])
horizontal_stack=np.hstack((stack1,stack2))
vertical_stack=np.vstack((stack1,stack2))
print("HORIZONTAL STACK:\n",horizontal_stack)
print("VERTICAL STACK:\n",vertical_stack)


HORIZONTAL STACK:
 [1 2 3 4 5 6 7 8]
VERTICAL STACK:
 [[1 2 3 4]
 [5 6 7 8]]


In [21]:
horizontal_stack.shape


(8,)

In [22]:
vertical_stack.shape

(2, 4)

In [23]:
applati=np.ravel(vertical_stack)

In [24]:
print(applati)

[1 2 3 4 5 6 7 8]


In [25]:
#SLICING
# 1D
a= np.array([10, 20, 30, 40, 50])

In [26]:
a[1:4]

array([20, 30, 40])

In [27]:
a[:3]

array([10, 20, 30])

In [28]:
a[2:]

array([30, 40, 50])

In [29]:
a[::2]

array([10, 30, 50])

In [30]:
a[::-1]

array([50, 40, 30, 20, 10])

In [31]:
# 2D
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [32]:
print(b[0, 1])

2


In [33]:
print(b[0:2, 1:3])

[[2 3]
 [5 6]]


In [34]:
print(b[:, 1])

[2 5 8]


In [35]:
print(b[1, :])

[4 5 6]


In [36]:
# RESUME RAPIDE
# --- Création de tableaux ---
a = np.array([1, 2, 3])                  # vecteur 1D
A = np.array([[1, 2], [3, 4]])           # matrice 2D
Z = np.zeros((3, 3))                     # matrice de zéros
I = np.eye(3)                            # matrice identité
R = np.random.randn(4, 4)               # matrice aléatoire (loi normale)



In [37]:
print("1-\n",a)
print("2-\n",A)
print("3-\n",Z)
print("4-\n",I)
print("5-\n",R)

1-
 [1 2 3]
2-
 [[1 2]
 [3 4]]
3-
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
4-
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
5-
 [[-0.79182726 -1.35088007 -1.75135478  0.09040511]
 [ 0.7996965   0.00881443 -1.40536066 -1.05135831]
 [-0.51345382  0.24968195  0.27339126  0.60892226]
 [-1.43236011 -1.06269902 -0.61899981 -2.11657273]]


In [38]:
# --- Opérations de base ---
b = np.array([4, 5, 6])
print(a + b)        # addition élément par élément
print(a * b)        # multiplication élément par élément (PAS matricielle)
print(a @ b)        # produit scalaire (dot product)
print(A @ A)        # multiplication MATRICIELLE

[5 7 9]
[ 4 10 18]
32
[[ 7 10]
 [15 22]]


In [39]:
# --- Slicing ---
M = np.arange(16).reshape(4, 4)
print(M[0, :])      # première ligne
print(M[:, 1])      # deuxième colonne
print(M[1:3, 1:3])  # sous-matrice

[0 1 2 3]
[ 1  5  9 13]
[[ 5  6]
 [ 9 10]]


In [40]:
# --- Broadcasting (très important en ML) ---
v = np.array([1, 2, 3, 4])
print(M + v)        # ajoute v à chaque ligne de M automatiquement

[[ 1  3  5  7]
 [ 5  7  9 11]
 [ 9 11 13 15]
 [13 15 17 19]]


In [41]:
# --- Fonctions utiles ---
print(A.T)          # transposée
print(A.shape)      # dimensions
print(np.linalg.inv(A))   # inverse
print(np.linalg.det(A))   # déterminant
print(np.mean(M, axis=0)) # moyenne par colonne
print(np.std(M))          # écart-type

[[1 3]
 [2 4]]
(2, 2)
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
[6. 7. 8. 9.]
4.6097722286464435
