<a href="https://colab.research.google.com/github/harifaly/Python_for_data_science/blob/main/_numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
print('SALAMA DAHOLO\n content im english ;)')

SALAMA DAHOLO
 content im english ;)


In [2]:
# To import the Package
import numpy as np

# Basic Functions


In [3]:
# To print the version of NumPy
print(np.__version__)

2.0.2


In [10]:
# To create An Array in NumPy
myarr1 = np.array([24,12,54,8]) # we can also pass tuples,array,list in np.array() method
print(myarr1) # 1D Array

[24 12 54  8]


In [11]:
# To print size of An Array
print(myarr1.itemsize)

8


In [12]:
# To Sort the Array
print(np.sort(myarr1))

[ 8 12 24 54]


In [13]:
# To print the type of a Data Structure
print(type(myarr1))

<class 'numpy.ndarray'>


In [14]:
# To get the shape of an array i.e (row,column)
myarr1.shape

(4,)

In [15]:
# To print the data type of an array
myarr1.dtype

dtype('int64')

In [16]:
# For Itreating 1D Array
for x in myarr1:
    print(x)

24
12
54
8


In [18]:
# To access the Element of An Array (like in C if you begin to code in that lang)
myarr1[2]
print(myarr1[2])

54


In [19]:
# To change the data in an 1D array with its index
myarr1[3] = 27
print(myarr1)

[24 12 54 27]


# ARRAY

In [ ]:
table1=np.array([1,2,3,4])

In [ ]:
print (table1)

[1 2 3 4]


In [ ]:
table2=np.array([1,2,3])

In [ ]:
print(table2)

[1 2 3]


In [ ]:
table3=np.zeros((2,3))

In [ ]:
table3.shape

(2, 3)

In [ ]:
print(table3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
table4=np.ones((2,2))

In [ ]:
print(table4)

[[1. 1.]
 [1. 1.]]


In [ ]:
table4=np.ones((4,5))

In [ ]:
print(table4)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
table5=np.random.randn(5)
table6=np.random.randn(5,2)

**Stacking Array**

In [ ]:
print("TABLE 5:\n",table5)
print("TABLE 6:\n",table6)

TABLE 5:
 [ 1.70221576 -0.17703171  0.07366828  0.31189591  0.61965787]
TABLE 6:
 [[ 0.16152369  0.52748097]
 [-0.70841843 -1.66249755]
 [ 0.90419886  0.49791333]
 [-0.92608603  0.96695052]
 [ 0.99976076 -0.52783143]]


In [ ]:
stack1= np.array([1,2,3,4])
stack2= np.array([5,6,7,8])
horizontal_stack=np.hstack((stack1,stack2))
vertical_stack=np.vstack((stack1,stack2))
print("HORIZONTAL STACK:\n",horizontal_stack)
print("VERTICAL STACK:\n",vertical_stack)


HORIZONTAL STACK:
 [1 2 3 4 5 6 7 8]
VERTICAL STACK:
 [[1 2 3 4]
 [5 6 7 8]]


In [ ]:
horizontal_stack.shape


(8,)

In [ ]:
vertical_stack.shape

(2, 4)

In [ ]:
applati=np.ravel(vertical_stack)

In [ ]:
print(applati)

[1 2 3 4 5 6 7 8]


In [ ]:
#SLICING
# 1D
a= np.array([10, 20, 30, 40, 50])

In [ ]:
# Prend de l’indice 1 à 3 (4 exclu)
a[1:4]

array([20, 30, 40])

In [ ]:
# Début jusqu’à l’indice 2
a[:3]

array([10, 20, 30])

In [ ]:
# De l’indice 2 jusqu’à la fin
a[2:]

array([30, 40, 50])

In [ ]:
# Pas de 2 (un élément sur deux)
a[::2]

array([10, 30, 50])

In [ ]:
# Inverser le tableau
a[::-1]

array([50, 40, 30, 20, 10])

In [ ]:
# 2D
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
# (ligne 0, colonne 1)
print(b[0, 1])

2


In [ ]:
# Lignes 0 à 1, colonnes 1 à 2
print(b[0:2, 1:3])

[[2 3]
 [5 6]]


In [ ]:
# Toute la colonne 1
print(b[:, 1])

[2 5 8]


In [ ]:
# Toute la ligne 1
print(b[1, :])

[4 5 6]


In [ ]:
# ------- SUBSETTING--------
a = np.array([10, 20, 30, 40, 50])

In [ ]:
# On garde seulement les valeurs supérieures à 25
print(a[a > 25])

[30 40 50]


In [ ]:
# Multiples de 20
print(a[a % 20 == 0])

[20 40]


In [ ]:
print(a[(a > 10) & (a < 50)])

[20 30 40]


In [ ]:
# ________Subsetting avec indices (fancy indexing)___________

In [ ]:
# On choisit des positions spécifiques
print(a[[0, 2, 4]])

[10 30 50]


In [ ]:
# _________Subsetting en 2D (matrice)________

In [ ]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
# Condition :
print(b[b > 5])

# Résultat devient 1D (important)

[6 7 8 9]


In [ ]:
# Par lignes :
print(b[b[:, 1] > 4])

# On garde les lignes où la colonne 1 > 4

[[4 5 6]
 [7 8 9]]


In [ ]:
c = np.array([
    [1, 2, 3,4],
    [4, 5, 6,5],
    [7, 8, 9,6]
])

In [ ]:
subs1=c[::2,::2]
# on saute de 2 pas pour chaque ligne et cols

In [ ]:
print(subs1)

[[1 3]
 [7 9]]


RESUME RAPIDE

In [ ]:
# RESUME RAPIDE
# ------ Création de tableaux ------
a = np.array([1, 2, 3])                  # vecteur 1D
A = np.array([[1, 2], [3, 4]])           # matrice 2D
Z = np.zeros((3, 3))                     # matrice de zéros
I = np.eye(3)                            # matrice identité
R = np.random.randn(4, 4)               # matrice aléatoire (loi normale)



In [ ]:
print("1-\n",a)
print("2-\n",A)
print("3-\n",Z)
print("4-\n",I)
print("5-\n",R)

1-
 [1 2 3]
2-
 [[1 2]
 [3 4]]
3-
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
4-
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
5-
 [[ 0.84703535 -0.53999432 -1.00119642 -0.60812572]
 [-0.52545906 -0.38020761  0.09215828  0.24013805]
 [-0.93561576  0.0531621  -1.67419268 -0.51415243]
 [ 0.69006347  0.05767838 -0.37722056  0.2155919 ]]


In [ ]:
# --- Opérations de base ---
b = np.array([4, 5, 6])
print(a + b)        # addition élément par élément
print(a * b)        # multiplication élément par élément (PAS matricielle)
print(a @ b)        # produit scalaire (dot product)
print(A @ A)        # multiplication MATRICIELLE

[5 7 9]
[ 4 10 18]
32
[[ 7 10]
 [15 22]]


In [ ]:
# --- Slicing ---
M = np.arange(16).reshape(4, 4)
print(M[0, :])      # première ligne
print(M[:, 1])      # deuxième colonne
print(M[1:3, 1:3])  # sous-matrice

[0 1 2 3]
[ 1  5  9 13]
[[ 5  6]
 [ 9 10]]


In [ ]:
# --- Broadcasting (très important en ML) ---
v = np.array([1, 2, 3, 4])
print(M + v)        # ajoute v à chaque ligne de M automatiquement

[[ 1  3  5  7]
 [ 5  7  9 11]
 [ 9 11 13 15]
 [13 15 17 19]]


Fonction utile

In [ ]:
# --- Fonctions utiles ---
print(A.T)          # transposée
print(A.shape)      # dimensions
print(np.linalg.inv(A))   # inverse
print(np.linalg.det(A))   # déterminant
print(np.mean(M, axis=0)) # moyenne par colonne
print(np.std(M))          # écart-type

[[1 3]
 [2 4]]
(2, 2)
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
[6. 7. 8. 9.]
4.6097722286464435
