<a href="https://colab.research.google.com/github/harifaly/Python_for_data_science/blob/main/_numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
print('hello world')

hello world


In [44]:
import numpy as np

# ARRAY

In [45]:
table1=np.array([1,2,3,4])

In [46]:
print (table1)

[1 2 3 4]


In [47]:
table2=np.array([1,2,3])

In [48]:
print(table2)

[1 2 3]


In [49]:
table3=np.zeros((2,3))

In [50]:
table3.shape

(2, 3)

In [51]:
print(table3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [52]:
table4=np.ones((2,2))

In [53]:
print(table4)

[[1. 1.]
 [1. 1.]]


In [54]:
table4=np.ones((4,5))

In [55]:
print(table4)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [56]:
table5=np.random.randn(5)
table6=np.random.randn(5,2)

In [57]:
print("TABLE 5:\n",table5)
print("TABLE 6:\n",table6)

TABLE 5:
 [ 1.70221576 -0.17703171  0.07366828  0.31189591  0.61965787]
TABLE 6:
 [[ 0.16152369  0.52748097]
 [-0.70841843 -1.66249755]
 [ 0.90419886  0.49791333]
 [-0.92608603  0.96695052]
 [ 0.99976076 -0.52783143]]


In [58]:
stack1= np.array([1,2,3,4])
stack2= np.array([5,6,7,8])
horizontal_stack=np.hstack((stack1,stack2))
vertical_stack=np.vstack((stack1,stack2))
print("HORIZONTAL STACK:\n",horizontal_stack)
print("VERTICAL STACK:\n",vertical_stack)


HORIZONTAL STACK:
 [1 2 3 4 5 6 7 8]
VERTICAL STACK:
 [[1 2 3 4]
 [5 6 7 8]]


In [59]:
horizontal_stack.shape


(8,)

In [60]:
vertical_stack.shape

(2, 4)

In [61]:
applati=np.ravel(vertical_stack)

In [62]:
print(applati)

[1 2 3 4 5 6 7 8]


In [63]:
#SLICING
# 1D
a= np.array([10, 20, 30, 40, 50])

In [64]:
# Prend de l’indice 1 à 3 (4 exclu)
a[1:4]

array([20, 30, 40])

In [65]:
# Début jusqu’à l’indice 2
a[:3]

array([10, 20, 30])

In [66]:
# De l’indice 2 jusqu’à la fin
a[2:]

array([30, 40, 50])

In [67]:
# Pas de 2 (un élément sur deux)
a[::2]

array([10, 30, 50])

In [68]:
# Inverser le tableau
a[::-1]

array([50, 40, 30, 20, 10])

In [69]:
# 2D
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [70]:
# (ligne 0, colonne 1)
print(b[0, 1])

2


In [71]:
# Lignes 0 à 1, colonnes 1 à 2
print(b[0:2, 1:3])

[[2 3]
 [5 6]]


In [72]:
# Toute la colonne 1
print(b[:, 1])

[2 5 8]


In [73]:
# Toute la ligne 1
print(b[1, :])

[4 5 6]


In [82]:
# ------- SUBSETTING--------
a = np.array([10, 20, 30, 40, 50])

In [83]:
# On garde seulement les valeurs supérieures à 25
print(a[a > 25])

[30 40 50]


In [85]:
# Multiples de 20
print(a[a % 20 == 0])

[20 40]


In [86]:
print(a[(a > 10) & (a < 50)])

[20 30 40]


In [ ]:
# ________Subsetting avec indices (fancy indexing)___________

In [87]:
# On choisit des positions spécifiques
print(a[[0, 2, 4]])

[10 30 50]


In [ ]:
# _________Subsetting en 2D (matrice)________

In [88]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [89]:
# Condition :
print(b[b > 5])

# Résultat devient 1D (important)

[6 7 8 9]


In [90]:
# Par lignes :
print(b[b[:, 1] > 4])

# On garde les lignes où la colonne 1 > 4

[[4 5 6]
 [7 8 9]]


In [92]:
c = np.array([
    [1, 2, 3,4],
    [4, 5, 6,5],
    [7, 8, 9,6]
])

In [93]:
subs1=c[::2,::2]
# on saute de 2 pas pour chaque ligne et cols

In [94]:
print(subs1)

[[1 3]
 [7 9]]


RESUME RAPIDE

In [74]:
# RESUME RAPIDE
# ------ Création de tableaux ------
a = np.array([1, 2, 3])                  # vecteur 1D
A = np.array([[1, 2], [3, 4]])           # matrice 2D
Z = np.zeros((3, 3))                     # matrice de zéros
I = np.eye(3)                            # matrice identité
R = np.random.randn(4, 4)               # matrice aléatoire (loi normale)



In [75]:
print("1-\n",a)
print("2-\n",A)
print("3-\n",Z)
print("4-\n",I)
print("5-\n",R)

1-
 [1 2 3]
2-
 [[1 2]
 [3 4]]
3-
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
4-
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
5-
 [[ 0.84703535 -0.53999432 -1.00119642 -0.60812572]
 [-0.52545906 -0.38020761  0.09215828  0.24013805]
 [-0.93561576  0.0531621  -1.67419268 -0.51415243]
 [ 0.69006347  0.05767838 -0.37722056  0.2155919 ]]


In [76]:
# --- Opérations de base ---
b = np.array([4, 5, 6])
print(a + b)        # addition élément par élément
print(a * b)        # multiplication élément par élément (PAS matricielle)
print(a @ b)        # produit scalaire (dot product)
print(A @ A)        # multiplication MATRICIELLE

[5 7 9]
[ 4 10 18]
32
[[ 7 10]
 [15 22]]


In [77]:
# --- Slicing ---
M = np.arange(16).reshape(4, 4)
print(M[0, :])      # première ligne
print(M[:, 1])      # deuxième colonne
print(M[1:3, 1:3])  # sous-matrice

[0 1 2 3]
[ 1  5  9 13]
[[ 5  6]
 [ 9 10]]


In [78]:
# --- Broadcasting (très important en ML) ---
v = np.array([1, 2, 3, 4])
print(M + v)        # ajoute v à chaque ligne de M automatiquement

[[ 1  3  5  7]
 [ 5  7  9 11]
 [ 9 11 13 15]
 [13 15 17 19]]


Fonction utile

In [79]:
# --- Fonctions utiles ---
print(A.T)          # transposée
print(A.shape)      # dimensions
print(np.linalg.inv(A))   # inverse
print(np.linalg.det(A))   # déterminant
print(np.mean(M, axis=0)) # moyenne par colonne
print(np.std(M))          # écart-type

[[1 3]
 [2 4]]
(2, 2)
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
[6. 7. 8. 9.]
4.6097722286464435
